# Generated by Django 3.2 on 2021-04-14 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title of post', max_length=255)),
                ('description', models.TextField(help_text='Enter a short description', max_length=1000, verbose_name='Post description')),
                ('content', models.TextField(verbose_name='Post content')),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Pub date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
